var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/hotel-social-media-management/page.js")
R.c("server/chunks/ssr/_0fnn34f._.js")
R.c("server/chunks/ssr/[root-of-the-server]__01ms323._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_1cxqukj.js")
R.c("server/chunks/ssr/node_modules_next_dist_0gqiype._.js")
R.c("server/chunks/ssr/[root-of-the-server]__10ldt1g._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0g84hko._.js")
R.c("server/chunks/ssr/[root-of-the-server]__01tj5wf._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0wpq8j3._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0symwr9.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0l_sp0x.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0-o-goa.js")
R.c("server/chunks/ssr/_next-internal_server_app_hotel-social-media-management_page_actions_0avv2nf.js")
R.m(62758)
module.exports=R.m(62758).exports
