// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../app/account-pitch-planner/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/account-pitch-planner">> = Specific
  const handler = {} as typeof import("../../app/account-pitch-planner/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../app/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/auth/callback/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/callback">> = Specific
  const handler = {} as typeof import("../../app/auth/callback/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/candidates/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/candidates">> = Specific
  const handler = {} as typeof import("../../app/candidates/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/case-studies/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/case-studies">> = Specific
  const handler = {} as typeof import("../../app/case-studies/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/client-onboarding/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/client-onboarding">> = Specific
  const handler = {} as typeof import("../../app/client-onboarding/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/companies/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/companies">> = Specific
  const handler = {} as typeof import("../../app/companies/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/contact-candidates/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/contact-candidates">> = Specific
  const handler = {} as typeof import("../../app/contact-candidates/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/contact/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/contact">> = Specific
  const handler = {} as typeof import("../../app/contact/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/contacts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/contacts">> = Specific
  const handler = {} as typeof import("../../app/contacts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/creative-gap-review/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/creative-gap-review">> = Specific
  const handler = {} as typeof import("../../app/creative-gap-review/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/creative-gap-reviews/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/creative-gap-reviews">> = Specific
  const handler = {} as typeof import("../../app/creative-gap-reviews/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/creative-output/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/creative-output">> = Specific
  const handler = {} as typeof import("../../app/creative-output/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/daily/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/daily">> = Specific
  const handler = {} as typeof import("../../app/daily/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../app/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/followups/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/followups">> = Specific
  const handler = {} as typeof import("../../app/followups/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/growth/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/growth">> = Specific
  const handler = {} as typeof import("../../app/growth/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/hiring-signals/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/hiring-signals">> = Specific
  const handler = {} as typeof import("../../app/hiring-signals/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/hospitality-creative-support/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/hospitality-creative-support">> = Specific
  const handler = {} as typeof import("../../app/hospitality-creative-support/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/hospitality-resource-vault/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/hospitality-resource-vault">> = Specific
  const handler = {} as typeof import("../../app/hospitality-resource-vault/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/hotel-creative-scorecard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/hotel-creative-scorecard">> = Specific
  const handler = {} as typeof import("../../app/hotel-creative-scorecard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/hotel-marketing-cost-savings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/hotel-marketing-cost-savings">> = Specific
  const handler = {} as typeof import("../../app/hotel-marketing-cost-savings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/hotel-restaurant-event-promos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/hotel-restaurant-event-promos">> = Specific
  const handler = {} as typeof import("../../app/hotel-restaurant-event-promos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/hotel-social-media-management/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/hotel-social-media-management">> = Specific
  const handler = {} as typeof import("../../app/hotel-social-media-management/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/hotel-video-marketing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/hotel-video-marketing">> = Specific
  const handler = {} as typeof import("../../app/hotel-video-marketing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/intake/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/intake">> = Specific
  const handler = {} as typeof import("../../app/intake/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/intro-sources/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/intro-sources">> = Specific
  const handler = {} as typeof import("../../app/intro-sources/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/linkedin-scorecard-launch/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/linkedin-scorecard-launch">> = Specific
  const handler = {} as typeof import("../../app/linkedin-scorecard-launch/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/messages/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/messages">> = Specific
  const handler = {} as typeof import("../../app/messages/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/outreach/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/outreach">> = Specific
  const handler = {} as typeof import("../../app/outreach/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/packages/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/packages">> = Specific
  const handler = {} as typeof import("../../app/packages/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/partners/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/partners">> = Specific
  const handler = {} as typeof import("../../app/partners/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/proposal-generator/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/proposal-generator">> = Specific
  const handler = {} as typeof import("../../app/proposal-generator/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/prospects/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/prospects">> = Specific
  const handler = {} as typeof import("../../app/prospects/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/restaurant-creative-support/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/restaurant-creative-support">> = Specific
  const handler = {} as typeof import("../../app/restaurant-creative-support/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/sales-assets/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sales-assets">> = Specific
  const handler = {} as typeof import("../../app/sales-assets/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/scorecard-submissions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/scorecard-submissions">> = Specific
  const handler = {} as typeof import("../../app/scorecard-submissions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings">> = Specific
  const handler = {} as typeof import("../../app/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/spa-salon-creative-support/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/spa-salon-creative-support">> = Specific
  const handler = {} as typeof import("../../app/spa-salon-creative-support/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/suppression/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/suppression">> = Specific
  const handler = {} as typeof import("../../app/suppression/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/templates/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/templates">> = Specific
  const handler = {} as typeof import("../../app/templates/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/unsubscribe/[token]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/unsubscribe/[token]">> = Specific
  const handler = {} as typeof import("../../app/unsubscribe/[token]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/contact/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/contact">> = Specific
  const handler = {} as typeof import("../../app/api/contact/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/creative-gap-review/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/creative-gap-review">> = Specific
  const handler = {} as typeof import("../../app/api/creative-gap-review/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/hunter/domain-search/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/hunter/domain-search">> = Specific
  const handler = {} as typeof import("../../app/api/hunter/domain-search/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/hunter/find-email/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/hunter/find-email">> = Specific
  const handler = {} as typeof import("../../app/api/hunter/find-email/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/hunter/verify-email/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/hunter/verify-email">> = Specific
  const handler = {} as typeof import("../../app/api/hunter/verify-email/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/prospects/draft/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/prospects/draft">> = Specific
  const handler = {} as typeof import("../../app/api/prospects/draft/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/prospects/hunter/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/prospects/hunter">> = Specific
  const handler = {} as typeof import("../../app/api/prospects/hunter/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/research-company/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/research-company">> = Specific
  const handler = {} as typeof import("../../app/api/research-company/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/research/candidate-action/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/research/candidate-action">> = Specific
  const handler = {} as typeof import("../../app/api/research/candidate-action/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/research/diagnostics/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/research/diagnostics">> = Specific
  const handler = {} as typeof import("../../app/api/research/diagnostics/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/research/promote/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/research/promote">> = Specific
  const handler = {} as typeof import("../../app/api/research/promote/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/research/reject/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/research/reject">> = Specific
  const handler = {} as typeof import("../../app/api/research/reject/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/research/run/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/research/run">> = Specific
  const handler = {} as typeof import("../../app/api/research/run/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/research/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/research/status">> = Specific
  const handler = {} as typeof import("../../app/api/research/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/research/test-firecrawl-search/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/research/test-firecrawl-search">> = Specific
  const handler = {} as typeof import("../../app/api/research/test-firecrawl-search/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/research/test-firecrawl/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/research/test-firecrawl">> = Specific
  const handler = {} as typeof import("../../app/api/research/test-firecrawl/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/research/test-google/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/research/test-google">> = Specific
  const handler = {} as typeof import("../../app/api/research/test-google/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/schedule-approved-today/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/schedule-approved-today">> = Specific
  const handler = {} as typeof import("../../app/api/schedule-approved-today/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/scorecard/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/scorecard">> = Specific
  const handler = {} as typeof import("../../app/api/scorecard/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/scorecard/submission/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/scorecard/submission">> = Specific
  const handler = {} as typeof import("../../app/api/scorecard/submission/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/scorecard/website-preaudit/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/scorecard/website-preaudit">> = Specific
  const handler = {} as typeof import("../../app/api/scorecard/website-preaudit/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/send-approved/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/send-approved">> = Specific
  const handler = {} as typeof import("../../app/api/send-approved/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/send-due/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/send-due">> = Specific
  const handler = {} as typeof import("../../app/api/send-due/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/send-test/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/send-test">> = Specific
  const handler = {} as typeof import("../../app/api/send-test/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/signals/hiring/save/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/signals/hiring/save">> = Specific
  const handler = {} as typeof import("../../app/api/signals/hiring/save/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/signals/hiring/search/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/signals/hiring/search">> = Specific
  const handler = {} as typeof import("../../app/api/signals/hiring/search/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/stripe/checkout-link/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/stripe/checkout-link">> = Specific
  const handler = {} as typeof import("../../app/api/stripe/checkout-link/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/stripe/invoice-link/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/stripe/invoice-link">> = Specific
  const handler = {} as typeof import("../../app/api/stripe/invoice-link/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/stripe/portal-link/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/stripe/portal-link">> = Specific
  const handler = {} as typeof import("../../app/api/stripe/portal-link/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/stripe/webhook/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/stripe/webhook">> = Specific
  const handler = {} as typeof import("../../app/api/stripe/webhook/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/website-audit/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/website-audit">> = Specific
  const handler = {} as typeof import("../../app/api/website-audit/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
