var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/unsubscribe/[token]/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0m_2yjr._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_1h0ur1s.js")
R.c("server/chunks/ssr/node_modules_next_dist_0gqiype._.js")
R.c("server/chunks/ssr/app_unsubscribe_[token]_page_tsx_047pafj._.js")
R.c("server/chunks/ssr/[root-of-the-server]__10ldt1g._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0g84hko._.js")
R.c("server/chunks/ssr/[root-of-the-server]__01tj5wf._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0wpq8j3._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0symwr9.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0l_sp0x.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0-o-goa.js")
R.c("server/chunks/ssr/_next-internal_server_app_unsubscribe_[token]_page_actions_1o5i503.js")
R.m(16845)
module.exports=R.m(16845).exports
