// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/account-pitch-planner" | "/admin" | "/auth/callback" | "/candidates" | "/case-studies" | "/client-onboarding" | "/companies" | "/contact" | "/contact-candidates" | "/contacts" | "/creative-gap-review" | "/creative-gap-reviews" | "/creative-output" | "/daily" | "/dashboard" | "/followups" | "/growth" | "/hiring-signals" | "/hospitality-creative-support" | "/hospitality-resource-vault" | "/hotel-creative-scorecard" | "/hotel-marketing-cost-savings" | "/hotel-restaurant-event-promos" | "/hotel-social-media-management" | "/hotel-video-marketing" | "/intake" | "/intro-sources" | "/linkedin-scorecard-launch" | "/login" | "/messages" | "/outreach" | "/packages" | "/partners" | "/promo-rescue" | "/proposal-generator" | "/prospects" | "/restaurant-creative-support" | "/sales-assets" | "/scorecard-submissions" | "/settings" | "/spa-salon-creative-support" | "/suppression" | "/templates" | "/unsubscribe/[token]"
type AppRouteHandlerRoutes = "/api/contact" | "/api/creative-gap-review" | "/api/hunter/domain-search" | "/api/hunter/find-email" | "/api/hunter/verify-email" | "/api/prospects/draft" | "/api/prospects/hunter" | "/api/research-company" | "/api/research/candidate-action" | "/api/research/diagnostics" | "/api/research/promote" | "/api/research/reject" | "/api/research/run" | "/api/research/status" | "/api/research/test-firecrawl" | "/api/research/test-firecrawl-search" | "/api/research/test-google" | "/api/schedule-approved-today" | "/api/scorecard" | "/api/scorecard/submission" | "/api/scorecard/website-preaudit" | "/api/send-approved" | "/api/send-due" | "/api/send-test" | "/api/signals/hiring/save" | "/api/signals/hiring/search" | "/api/stripe/checkout-link" | "/api/stripe/invoice-link" | "/api/stripe/portal-link" | "/api/stripe/webhook" | "/api/website-audit"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/account-pitch-planner": {}
  "/admin": {}
  "/api/contact": {}
  "/api/creative-gap-review": {}
  "/api/hunter/domain-search": {}
  "/api/hunter/find-email": {}
  "/api/hunter/verify-email": {}
  "/api/prospects/draft": {}
  "/api/prospects/hunter": {}
  "/api/research-company": {}
  "/api/research/candidate-action": {}
  "/api/research/diagnostics": {}
  "/api/research/promote": {}
  "/api/research/reject": {}
  "/api/research/run": {}
  "/api/research/status": {}
  "/api/research/test-firecrawl": {}
  "/api/research/test-firecrawl-search": {}
  "/api/research/test-google": {}
  "/api/schedule-approved-today": {}
  "/api/scorecard": {}
  "/api/scorecard/submission": {}
  "/api/scorecard/website-preaudit": {}
  "/api/send-approved": {}
  "/api/send-due": {}
  "/api/send-test": {}
  "/api/signals/hiring/save": {}
  "/api/signals/hiring/search": {}
  "/api/stripe/checkout-link": {}
  "/api/stripe/invoice-link": {}
  "/api/stripe/portal-link": {}
  "/api/stripe/webhook": {}
  "/api/website-audit": {}
  "/auth/callback": {}
  "/candidates": {}
  "/case-studies": {}
  "/client-onboarding": {}
  "/companies": {}
  "/contact": {}
  "/contact-candidates": {}
  "/contacts": {}
  "/creative-gap-review": {}
  "/creative-gap-reviews": {}
  "/creative-output": {}
  "/daily": {}
  "/dashboard": {}
  "/followups": {}
  "/growth": {}
  "/hiring-signals": {}
  "/hospitality-creative-support": {}
  "/hospitality-resource-vault": {}
  "/hotel-creative-scorecard": {}
  "/hotel-marketing-cost-savings": {}
  "/hotel-restaurant-event-promos": {}
  "/hotel-social-media-management": {}
  "/hotel-video-marketing": {}
  "/intake": {}
  "/intro-sources": {}
  "/linkedin-scorecard-launch": {}
  "/login": {}
  "/messages": {}
  "/outreach": {}
  "/packages": {}
  "/partners": {}
  "/promo-rescue": {}
  "/proposal-generator": {}
  "/prospects": {}
  "/restaurant-creative-support": {}
  "/sales-assets": {}
  "/scorecard-submissions": {}
  "/settings": {}
  "/spa-salon-creative-support": {}
  "/suppression": {}
  "/templates": {}
  "/unsubscribe/[token]": { "token": string; }
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
