import type {
  Company,
  Contact,
  Partner,
  Template,
  FollowUp,
  AppSettings,
} from "./types";

export const MOCK_COMPANIES: Company[] = [
  { id: "co-1", name: "Pinnacle Hospitality Group", website: "https://pinnaclehg.com", type: "hospitality_group", size: "large", location: "New York, NY", notes: "Multi-brand group operating 40+ properties across the Northeast and Southeast.", created_at: "2026-04-01T10:00:00Z", updated_at: "2026-05-15T10:00:00Z" },
  { id: "co-2", name: "Thorpe Hotel Management", website: "https://thorpehotels.com", type: "hotel_management_company", size: "medium", location: "Miami, FL", notes: "Owner-operated management company. 12 hotels. Pre-opening specialist.", created_at: "2026-04-05T09:00:00Z", updated_at: "2026-05-10T09:00:00Z" },
  { id: "co-3", name: "Urban Nest Boutique Collection", website: "https://urbannest.co", type: "boutique_hotel_group", size: "small", location: "Atlanta, GA", notes: "Boutique lifestyle portfolio expanding in the Southeast. 5 properties.", created_at: "2026-04-10T08:00:00Z", updated_at: "2026-05-25T08:00:00Z" },
  { id: "co-4", name: "Blue Horizon Management", website: "https://bluehorizonmgmt.com", type: "hotel_management_company", size: "large", location: "Houston, TX", notes: "Third-party management company. 15+ hotels across Texas and Gulf Coast.", created_at: "2026-03-20T10:00:00Z", updated_at: "2026-05-12T10:00:00Z" },
  { id: "co-5", name: "Summit Collection", website: "https://summitcollection.com", type: "boutique_hotel_group", size: "medium", location: "Denver, CO", notes: "6 independent boutique properties. Revenue strategy overhaul underway.", created_at: "2026-04-15T09:00:00Z", updated_at: "2026-06-01T09:00:00Z" },
  { id: "co-6", name: "Harbor View Hotel", website: "https://harborviewhotel.com", type: "independent_lifestyle_hotel", size: "solo", location: "Boston, MA", notes: "Independent lifestyle property. Stabilization project with restaurant relaunch.", created_at: "2026-05-01T07:00:00Z", updated_at: "2026-05-28T07:00:00Z" },
  { id: "co-7", name: "Drift Resorts", website: "https://driftresorts.com", type: "resort_group", size: "medium", location: "Scottsdale, AZ", notes: "8-property resort group. eCommerce and digital marketing overhaul.", created_at: "2026-05-10T08:00:00Z", updated_at: "2026-05-28T08:00:00Z" },
];

export const MOCK_CONTACTS: Contact[] = [
  { id: "ct-1", company_id: "co-1", first_name: "Sarah", last_name: "Kendall", title: "VP of Commercial Strategy", company_name: "Pinnacle Hospitality Group", company_type: "hospitality_group", contact_type: "buyer", email: "sarah.kendall@pinnaclehg.com", linkedin_url: "https://linkedin.com/in/sarahkendall", phone: "+1 212 555 0101", notes: "Multi-property portfolio in Northeast, considering turnaround assets.", status: "new", opted_out: false, opt_out_status: null, source: "manual", suppressed: false, last_contacted_at: null, created_at: "2026-05-01T10:00:00Z", updated_at: "2026-05-01T10:00:00Z" },
  { id: "ct-2", company_id: "co-2", first_name: "Marcus", last_name: "Thorpe", title: "CEO", company_name: "Thorpe Hotel Management", company_type: "hotel_management_company", contact_type: "buyer", email: "marcus@thorpehotels.com", linkedin_url: "https://linkedin.com/in/marcusthorpe", phone: "+1 305 555 0202", notes: "Owner of 12 hotels. Interested in pre-opening management contracts.", status: "follow_up_due", opted_out: false, opt_out_status: null, source: "referral", suppressed: false, last_contacted_at: "2026-05-10T09:00:00Z", created_at: "2026-04-15T08:00:00Z", updated_at: "2026-05-10T09:00:00Z" },
  { id: "ct-3", company_id: "co-6", first_name: "Diana", last_name: "Reyes", title: "Director of Sales & Marketing", company_name: "Harbor View Hotel", company_type: "independent_lifestyle_hotel", contact_type: "property_level", email: "dreyes@harborviewhotel.com", linkedin_url: null, phone: "+1 617 555 0303", notes: "Looking for F&B and events partnerships. Stabilization property.", status: "replied", opted_out: false, opt_out_status: null, source: "manual", suppressed: false, last_contacted_at: "2026-05-20T14:00:00Z", created_at: "2026-04-20T11:00:00Z", updated_at: "2026-05-20T14:00:00Z" },
  { id: "ct-4", company_id: "co-3", first_name: "James", last_name: "Okoye", title: "Founder & President", company_name: "Urban Nest Boutique Collection", company_type: "boutique_hotel_group", contact_type: "buyer", email: "james@urbannest.co", linkedin_url: "https://linkedin.com/in/jamesokoye", phone: null, notes: "Boutique lifestyle portfolio, expanding in Southeast. Owner of 5 properties.", status: "new", opted_out: false, opt_out_status: null, source: "manual", suppressed: false, last_contacted_at: null, created_at: "2026-05-25T09:00:00Z", updated_at: "2026-05-25T09:00:00Z" },
  { id: "ct-5", company_id: "co-6", first_name: "Linda", last_name: "Park", title: "General Manager", company_name: "Harbor View Hotel", company_type: "independent_lifestyle_hotel", contact_type: "property_level", email: "lpark@harborviewhotel.com", linkedin_url: "https://linkedin.com/in/lindapark", phone: "+1 617 555 0505", notes: "Stabilization project, restaurant relaunch in progress.", status: "queued", opted_out: false, opt_out_status: null, source: "manual", suppressed: false, last_contacted_at: "2026-05-28T10:00:00Z", created_at: "2026-05-03T07:00:00Z", updated_at: "2026-05-28T10:00:00Z" },
  { id: "ct-6", company_id: "co-4", first_name: "Robert", last_name: "Haines", title: "Area Director of Operations", company_name: "Blue Horizon Management", company_type: "hotel_management_company", contact_type: "partner", email: "r.haines@bluehorizonmgmt.com", linkedin_url: "https://linkedin.com/in/roberthaines", phone: "+1 404 555 0606", notes: "Management company with portfolio of 30+ assets. Commercial strategy partnership interest.", status: "call_booked", opted_out: false, opt_out_status: null, source: "referral", suppressed: false, last_contacted_at: "2026-05-30T11:00:00Z", created_at: "2026-04-01T09:00:00Z", updated_at: "2026-05-30T11:00:00Z" },
  { id: "ct-7", company_id: "co-7", first_name: "Tanya", last_name: "Morrison", title: "Director of eCommerce", company_name: "Drift Resorts", company_type: "resort_group", contact_type: "buyer", email: null, linkedin_url: "https://linkedin.com/in/tanyamorrison", phone: null, notes: "Digital marketing overhaul across 8 properties.", status: "new", opted_out: false, opt_out_status: null, source: "manual", suppressed: false, last_contacted_at: null, created_at: "2026-05-28T08:00:00Z", updated_at: "2026-05-28T08:00:00Z" },
  { id: "ct-8", company_id: "co-4", first_name: "Anthony", last_name: "Cruz", title: "Regional Director of Sales", company_name: "Blue Horizon Management", company_type: "hotel_management_company", contact_type: "buyer", email: "acruz@bluehorizonmgmt.com", linkedin_url: "https://linkedin.com/in/anthonycruz", phone: "+1 713 555 1414", notes: "Management company managing 15+ hotels. Multi-property focus.", status: "follow_up_due", opted_out: false, opt_out_status: null, source: "manual", suppressed: false, last_contacted_at: "2026-05-12T11:00:00Z", created_at: "2026-04-05T08:00:00Z", updated_at: "2026-05-12T11:00:00Z" },
  { id: "ct-9", company_id: "co-5", first_name: "Heather", last_name: "Simmons", title: "VP of Revenue Strategy", company_name: "Summit Collection", company_type: "boutique_hotel_group", contact_type: "buyer", email: "hsimmons@summitcollection.com", linkedin_url: "https://linkedin.com/in/heathersimmons", phone: "+1 303 555 1515", notes: "Boutique portfolio, 6 properties. Revenue strategy overhaul, looking at eCommerce.", status: "new", opted_out: false, opt_out_status: null, source: "manual", suppressed: false, last_contacted_at: null, created_at: "2026-06-01T11:00:00Z", updated_at: "2026-06-01T11:00:00Z" },
  { id: "ct-10", company_id: "co-1", first_name: "Carl", last_name: "Bennett", title: "Director of Marketing", company_name: "Pinnacle Hospitality Group", company_type: "hospitality_group", contact_type: "partner", email: "cbennett@pinnaclehg.com", linkedin_url: "https://linkedin.com/in/carlbennett", phone: "+1 212 555 1212", notes: "Partnership opportunity, portfolio of 40+ properties. Co-marketing interest.", status: "new", opted_out: false, opt_out_status: null, source: "manual", suppressed: false, last_contacted_at: null, created_at: "2026-06-01T10:00:00Z", updated_at: "2026-06-01T10:00:00Z" },
  { id: "ct-11", company_id: "co-2", first_name: "Nina", last_name: "Castillo", title: "COO", company_name: "Thorpe Hotel Management", company_type: "hotel_management_company", contact_type: "buyer", email: "nina@thorpehotels.com", linkedin_url: "https://linkedin.com/in/ninacastillo", phone: "+1 305 555 0909", notes: "Oversees operations. Key decision-maker on vendor relationships.", status: "sent", opted_out: false, opt_out_status: null, source: "manual", suppressed: false, last_contacted_at: "2026-05-22T13:00:00Z", created_at: "2026-04-10T10:00:00Z", updated_at: "2026-05-22T13:00:00Z" },
  { id: "ct-12", company_id: null, first_name: "Priya", last_name: "Mehta", title: "Owner", company_name: "The Ivy Boutique Inn", company_type: "independent_lifestyle_hotel", contact_type: "buyer", email: "priya@ivyboutiqueinn.com", linkedin_url: "https://linkedin.com/in/priyamehta", phone: "+1 415 555 1111", notes: "Owner-operator. Lifestyle property, events focus.", status: "new", opted_out: false, opt_out_status: null, source: "import", suppressed: false, last_contacted_at: null, created_at: "2026-06-01T09:30:00Z", updated_at: "2026-06-01T09:30:00Z" },
  { id: "ct-13", company_id: null, first_name: "Vanessa", last_name: "Liu", title: "Front Desk Supervisor", company_name: "The Grand Downtown", company_type: "branded_hotel", contact_type: "other", email: "vliu@grandowntown.com", linkedin_url: null, phone: null, notes: "", status: "opted_out", opted_out: true, opt_out_status: "active", source: "import", suppressed: false, last_contacted_at: "2026-01-15T10:00:00Z", created_at: "2026-01-01T10:00:00Z", updated_at: "2026-01-15T10:00:00Z" },
];

export const MOCK_PARTNERS: Partner[] = [
  { id: "p-1", name: "Alex Chen", company: "Chen Hospitality Advisors", email: "alex@chenhospitality.com", phone: "+1 415 555 2001", linkedin_url: "https://linkedin.com/in/alexchen", partnership_type: "referral", commission_type: "percentage", commission_value: 10, status: "active", notes: "Strong network in boutique hotel space. Referred 3 clients this year.", referral_count: 3, created_at: "2026-01-15T10:00:00Z", updated_at: "2026-05-01T10:00:00Z" },
  { id: "p-2", name: "Maya Williams", company: "Meridian Creative Agency", email: "maya@meridiancreative.co", phone: "+1 646 555 2002", linkedin_url: "https://linkedin.com/in/mayawilliams", partnership_type: "agency", commission_type: "flat", commission_value: 2500, status: "active", notes: "Full-service agency. White-label rev strategy for her hotel clients.", referral_count: 5, created_at: "2026-02-01T10:00:00Z", updated_at: "2026-05-20T10:00:00Z" },
  { id: "p-3", name: "David Torres", company: "Torres Hotel Tech", email: "dtorres@torreshoteltech.com", phone: "+1 312 555 2003", linkedin_url: "https://linkedin.com/in/davidtorres", partnership_type: "tech", commission_type: "percentage", commission_value: 15, status: "prospect", notes: "PMS integrations. Potential co-marketing on commercial strategy content.", referral_count: 0, created_at: "2026-05-10T10:00:00Z", updated_at: "2026-05-10T10:00:00Z" },
];

export const MOCK_TEMPLATES: Template[] = [
  { id: "tpl-1", name: "Intro – Hotel Owner / Founder", type: "email", subject: "Quick intro + hospitality revenue question", body: "Hi {{first_name}},\n\nI came across {{company}} and was genuinely impressed by what you're building.\n\nI work with independent hotel owners and boutique groups to unlock commercial growth — specifically around direct bookings, F&B revenue, and corporate contract strategy.\n\nWould you be open to a quick 20-minute call this week?\n\nBest,\n{{sender_name}}\n\n{{opt_out_line}}", tags: ["owner", "founder", "intro"], created_at: "2026-01-10T10:00:00Z", updated_at: "2026-05-01T10:00:00Z" },
  { id: "tpl-2", name: "Intro – Management Company", type: "email", subject: "Partnership opportunity for your portfolio", body: "Hi {{first_name}},\n\nI work with hotel management companies to drive commercial performance across their portfolio.\n\nGiven {{company}}'s portfolio, I think there's a strong opportunity to explore a strategic partnership.\n\nWould you have 20 minutes for a call this week?\n\nBest,\n{{sender_name}}\n\n{{opt_out_line}}", tags: ["management_company", "portfolio", "intro"], created_at: "2026-01-15T10:00:00Z", updated_at: "2026-04-01T10:00:00Z" },
  { id: "tpl-3", name: "LinkedIn Connection Request", type: "linkedin", subject: null, body: "Hi {{first_name}}, I work with hotel owners and management companies on commercial growth strategy — noticed your work at {{company}} and thought there might be a great fit. Would love to connect!", tags: ["linkedin", "connection", "intro"], created_at: "2026-02-01T10:00:00Z", updated_at: "2026-04-15T10:00:00Z" },
  { id: "tpl-4", name: "Follow-up – No Response (Day 7)", type: "email", subject: "Re: Quick intro + hospitality revenue question", body: "Hi {{first_name}},\n\nJust wanted to bump this up in case my last message got buried.\n\nI know timing is everything — if now isn't the right moment, I'm happy to reconnect whenever works better.\n\nBest,\n{{sender_name}}\n\n{{opt_out_line}}", tags: ["follow-up", "no-response"], created_at: "2026-02-15T10:00:00Z", updated_at: "2026-04-01T10:00:00Z" },
  { id: "tpl-5", name: "Follow-up – After Call", type: "followup", subject: "Great connecting — next steps", body: "Hi {{first_name}},\n\nIt was great speaking with you today. As discussed, here's a quick summary:\n\n- [Key point 1]\n- [Key point 2]\n\nNext steps:\n- [Action item]\n\nLooking forward to moving this forward.\n\nBest,\n{{sender_name}}", tags: ["follow-up", "post-call"], created_at: "2026-03-01T10:00:00Z", updated_at: "2026-04-01T10:00:00Z" },
  { id: "tpl-6", name: "Value-Prop Cold Email – Creative Partner", type: "email", subject: "A creative partner for {{company_name}} — without the overhead", body: "Hi {{first_name}},\n\nI've been following {{personalization_angle}} at {{company_name}} — it's exactly the kind of work great creative can amplify.\n\nWe act as an embedded creative team for {{specific_client_type}}, supporting {{specific_use_cases}}. The idea is simple: premium creative support at a fraction of the cost of hiring in-house — no payroll, benefits, software licenses, or onboarding overhead to carry.\n\nA snapshot of what that's produced for the brands we work with:\n{{stats_block}}\n\nWould you be open to a quick 20-minute call to see if there's a fit?\n\nBest,\n{{sender_name}}\n\n{{opt_out_line}}", tags: ["cold", "value-prop", "creative"], created_at: "2026-06-01T10:00:00Z", updated_at: "2026-06-01T10:00:00Z" },

  // ── Opportunity OS: outreach templates by lead_type ──
  // Short, human, value-led. Never lead with price; emphasize saving the overhead
  // of a full-time creative hire. tags[0] is the lead_type for easy matching.
  { id: "tpl-hiring", name: "Hiring Signal Contract Alternative", type: "email", subject: "Saw you're hiring a {{hiring_role_title}}", body: "Hi {{first_name}},\n\nNoticed {{company_name}} is hiring a {{hiring_role_title}} — usually a sign you need {{specific_use_cases}} handled well, and soon.\n\nBefore you carry a full-time salary, benefits, and software for it: we plug in as an embedded creative team and cover the same work on contract — no overhead, no onboarding lag.\n\n{{stats_block}}\n\nWorth a quick look? Happy to share examples: {{portfolio_url}}\n\nBest,\n{{sender_name}}\n\n{{opt_out_line}}", tags: ["hiring_signal", "contract-alternative"], created_at: "2026-06-05T10:00:00Z", updated_at: "2026-06-05T10:00:00Z" },

  { id: "tpl-overflow", name: "Hotel Marketing Overflow", type: "email", subject: "Extra creative hands for {{company_name}}", body: "Hi {{first_name}},\n\nMarketing teams at places like {{company_name}} usually have more ideas than capacity. When {{personalization_angle}} is in motion, {{specific_use_cases}} tends to pile up.\n\nWe act as overflow — an on-demand creative team that absorbs the extra without you adding headcount or carrying the overhead of a full-time hire.\n\n{{stats_block}}\n\nOpen to a quick look? {{portfolio_url}}\n\nBest,\n{{sender_name}}\n\n{{opt_out_line}}", tags: ["marketing_overflow", "overflow"], created_at: "2026-06-05T10:00:00Z", updated_at: "2026-06-05T10:00:00Z" },

  { id: "tpl-partner", name: "Hospitality Partner Referral", type: "email", subject: "Creative support for your hotel clients", body: "Hi {{first_name}},\n\nYou work closely with {{specific_client_type}}, and {{personalization_angle}} keeps coming up. A lot of them need {{specific_use_cases}} but can't justify a full-time creative hire.\n\nThat's exactly where we fit — embedded creative on contract, no overhead for them. Could be a clean add for your network (happy to make it worth your while).\n\n{{stats_block}}\n\nWorth comparing notes? {{portfolio_url}}\n\nBest,\n{{sender_name}}\n\n{{opt_out_line}}", tags: ["partner", "referral"], created_at: "2026-06-05T10:00:00Z", updated_at: "2026-06-05T10:00:00Z" },

  { id: "tpl-spa", name: "Spa / Wellness Creative Support", type: "email", subject: "Creative for the {{company_name}} spa & wellness story", body: "Hi {{first_name}},\n\nThe spa and wellness side of {{company_name}} is exactly the kind of experience that deserves strong creative — {{specific_use_cases}} that actually fill treatment calendars.\n\nWe handle that as a contract creative team, so you get the output without the overhead of a full-time hire.\n\n{{stats_block}}\n\nA few relevant examples: {{portfolio_url}}\n\nBest,\n{{sender_name}}\n\n{{opt_out_line}}", tags: ["spa", "wellness"], created_at: "2026-06-05T10:00:00Z", updated_at: "2026-06-05T10:00:00Z" },

  { id: "tpl-fnb", name: "F&B / Restaurant Event Promo Support", type: "email", subject: "Filling seats at {{company_name}}'s restaurant & events", body: "Hi {{first_name}},\n\nRestaurants and event spaces live or die on promotion. For {{company_name}}, {{specific_use_cases}} is usually what drives covers and bookings.\n\nWe run that as an embedded creative team on contract — same output as a full-time hire, none of the payroll or overhead.\n\n{{stats_block}}\n\nWant to see a few examples? {{portfolio_url}}\n\nBest,\n{{sender_name}}\n\n{{opt_out_line}}", tags: ["restaurant_fnb", "fnb", "events"], created_at: "2026-06-05T10:00:00Z", updated_at: "2026-06-05T10:00:00Z" },

  { id: "tpl-wedding", name: "Wedding / Events Venue Creative Support", type: "email", subject: "Booking more weddings & events at {{company_name}}", body: "Hi {{first_name}},\n\nWedding and event inquiries come down to how the venue is shown. For {{company_name}}, {{specific_use_cases}} is what turns browsers into booked dates.\n\nWe cover that as a contract creative team — premium output without the overhead of a full-time hire.\n\n{{stats_block}}\n\nA few venue examples: {{portfolio_url}}\n\nBest,\n{{sender_name}}\n\n{{opt_out_line}}", tags: ["wedding_events", "weddings", "events"], created_at: "2026-06-05T10:00:00Z", updated_at: "2026-06-05T10:00:00Z" },

  { id: "tpl-enterprise", name: "Multi-Property Hotel Group Pilot", type: "email", subject: "A creative pilot across {{company_name}}'s properties", body: "Hi {{first_name}},\n\nAcross a group like {{company_name}}, creative consistency is hard — every property needs {{specific_use_cases}}, and full-time hires per property don't scale.\n\nWe'd suggest a small pilot: embed as your creative team for one or two properties, prove it out, then roll wider. Contract model, so no per-property overhead.\n\n{{stats_block}}\n\nOpen to scoping a pilot? {{portfolio_url}}\n\nBest,\n{{sender_name}}\n\n{{opt_out_line}}", tags: ["enterprise_router", "multi-property", "pilot"], created_at: "2026-06-05T10:00:00Z", updated_at: "2026-06-05T10:00:00Z" },

  { id: "tpl-job", name: "Job Application + Contract Option", type: "email", subject: "Re: your {{hiring_role_title}} role — a flexible option", body: "Hi {{first_name}},\n\nI'm interested in the {{hiring_role_title}} role at {{company_name}}. One thing worth flagging: if you need the work covered now (or before a full-time hire is approved), I also offer the same on contract.\n\nThat means {{specific_use_cases}} handled immediately — no payroll, benefits, or onboarding overhead while you decide.\n\n{{stats_block}}\n\nPortfolio here: {{portfolio_url}}. Happy either way.\n\nBest,\n{{sender_name}}\n\n{{opt_out_line}}", tags: ["job_application", "contract-option"], created_at: "2026-06-05T10:00:00Z", updated_at: "2026-06-05T10:00:00Z" },
];

export const MOCK_FOLLOWUPS: FollowUp[] = [
  { id: "fu-1", contact_id: "ct-2", contact: {} as Contact, due_date: "2026-06-02", notes: "Follow up on the pre-opening proposal sent May 10. Check on timeline.", status: "pending", created_at: "2026-05-10T09:00:00Z", updated_at: "2026-05-10T09:00:00Z" },
  { id: "fu-2", contact_id: "ct-8", contact: {} as Contact, due_date: "2026-06-02", notes: "Schedule discovery call. Referenced multi-property strategy interest.", status: "pending", created_at: "2026-05-12T11:00:00Z", updated_at: "2026-05-12T11:00:00Z" },
  { id: "fu-3", contact_id: "ct-3", contact: {} as Contact, due_date: "2026-06-03", notes: "Check in on F&B and events partnership discussion.", status: "pending", created_at: "2026-05-20T14:00:00Z", updated_at: "2026-05-20T14:00:00Z" },
  { id: "fu-4", contact_id: "ct-6", contact: {} as Contact, due_date: "2026-06-05", notes: "Send partnership proposal deck before call.", status: "pending", created_at: "2026-05-30T11:00:00Z", updated_at: "2026-05-30T11:00:00Z" },
  { id: "fu-5", contact_id: "ct-11", contact: {} as Contact, due_date: "2026-05-30", notes: "No reply to last email. Try LinkedIn.", status: "completed", created_at: "2026-05-22T13:00:00Z", updated_at: "2026-05-30T10:00:00Z" },
];

export const MOCK_SETTINGS: AppSettings = {
  id: "settings-1",
  portfolio_url: "https://youragency.com/hospitality",
  sender_name: "Your Name",
  email_signature: "Your Name\nFounding Partner, [Your Agency]\nyourname@youragency.com\n+1 555 000 0000",
  mailing_address: "123 Main Street, Suite 100\nNew York, NY 10001",
  opt_out_line: "If you'd prefer not to receive emails from me, simply reply with 'unsubscribe' and I'll remove you immediately.",
  daily_send_goal: 40,
  updated_at: "2026-06-01T10:00:00Z",
};
